HW10_Django/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls'))
]

HW10_Django/hw_project/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='users'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add_quotes/', views.add_quotes, name='add_quotes'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_tag/', views.add_tag, name='add_tag')
]

HW10_Django/hw_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = 'users'


urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(
        template_name='users/signin.html',
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
        template_name='users/logout.html',
    ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

HW10_Django/hw_project/quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tag = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

HW10_Django/hw_project/users/models.py
from django.db import models

# Create your models here.

HW10_Django/hw_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, SelectMultiple, ModelChoiceField, \
    DateField, SelectDateWidget, Select
from .models import Quote, Author, Tag


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput())
    tag = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'), required=True, widget=SelectMultiple())
    author = ModelChoiceField(queryset=Author.objects.all().order_by('name'), required=True, widget=Select)

    class Meta:
        model = Quote
        fields = ['quote', 'tag', 'author']


class AuthorForm(ModelForm):
    name = CharField(min_length=2, required=True, widget=TextInput())
    born_date = CharField(required=True, widget=TextInput())
    born_location = CharField(max_length=250, required=True, widget=TextInput())
    description = CharField(min_length=2, widget=TextInput())

    class Meta:
        model = Author
        fields = ['name', 'born_date', 'born_location', 'description']


class TagForm(ModelForm):
    name = CharField(max_length=255, widget=TextInput)

    class Meta:
        model = Tag
        fields = ['name']

HW10_Django/hw_project/users/forms.py
from django.forms import ModelForm, CharField, TextInput, EmailField, EmailInput, PasswordInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    first_name = CharField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    last_name = CharField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    email = EmailField(max_length=100, required=True, widget=EmailInput(attrs={'class': 'form-control'}))
    password1 = CharField(max_length=20, min_length=6, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = CharField(max_length=20, min_length=6, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    password = CharField(max_length=20, min_length=6, required=True,
                         widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'password')

HW10_Django/hw_project/quotes/views.py
from bson import ObjectId
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import QuoteForm, AuthorForm, TagForm
from .utils import get_mongo_db


# Create your views here.
def main(request, page=1):
    db = get_mongo_db()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def add_quotes(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:users')
        else:
            return render(request, 'quotes/add_quotes.html', context={'form': QuoteForm()})
    return render(request, 'quotes/add_quotes.html', context={'form': QuoteForm()})



def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            print(new_quote)
            print('Dce ok')
            return redirect(to='quotes:users')
        else:
            return render(request, 'quotes/add_author.html', context={'form': AuthorForm(), 'message':'Wrong Data'})
    return render(request, 'quotes/add_author.html', context={'form': AuthorForm()})


def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            new_tag = form.save()
            return redirect(to='quotes:users')
        else:
            return render(request, 'quotes/add_tag.html', context={'form': TagForm(), 'message': 'Wrong Data'})
    return render(request, 'quotes/add_tag.html', context={'form': TagForm()})

HW10_Django/hw_project/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy


# Create your views here.
class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Вітаємо {username}. Ваш акаунт створено!')
            return redirect(to='users:login')
        return render(request, self.template_name, {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

HW10_Django/hw_project/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}

<form method="post" action="{% url 'quotes:add_author' %}">
  {% csrf_token %}
    <div class="row mb-3">
        <label>Name</label>
        {{ form.name }}
    </div>
    <div class="row mb-3">
        <label>Born date</label>
        {{ form.born_date }}
        <span>
            {{ form.errors.born_date }}
        </span>
    </div>
      <div class="row mb-3">
        <label>Born location</label>
        {{ form.born_location }}
        <span>
            {{ form.errors.born_location }}
        </span>
    </div>
          <div class="row mb-3">
        <label>Description</label>
        {{ form.description }}
        <span>
            {{ form.errors.description }}
        </span>
    </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset", class="btn btn-info">Reset</button>
</form>

{% endblock %}

HW10_Django/hw_project/quotes/templates/quotes/add_quotes.html
{% extends 'quotes/base.html' %}

{% block content %}

<form method="post" action="{% url 'quotes:add_quotes' %}">
  {% csrf_token %}
    <div class="row mb-3">
        <label>Quote</label>
        {{ form.quote }}
    </div>
    <div class="row mb-3">
        <label>Tag</label>
        {{ form.tag }}
        <span>
            {{ form.errors.tag }}
        </span>
    </div>
      <div class="row mb-3">
        <label>Author</label>
        {{ form.author }}
        <span>
            {{ form.errors.author }}
        </span>
    </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset", class="btn btn-info">Reset</button>
</form>

{% endblock %}

HW10_Django/hw_project/quotes/templates/quotes/add_tag.html
{% extends 'quotes/base.html' %}

{% block content %}

<form method="post" action="{% url 'quotes:add_tag' %}">
  {% csrf_token %}
    <div class="row mb-3">
        <label>Tag name</label>
        {{ form.name }}
    </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset", class="btn btn-info">Reset</button>
</form>

{% endblock %}

HW10_Django/hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Document</title>
</head>
<body>
<div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author</a>
                    <a href="{% url 'quotes:add_quotes' %}" class="btn btn-primary">Add Quote</a>
                    <a href="{% url 'quotes:add_tag' %}" class="btn btn-primary">Add Tag</a>
                    {% else %}
                    <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>


    {% block content %}
    {% endblock %}

    </div>

</body>
</html>

HW10_Django/hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote }}
            </span>
            <span>by <small class="author" itemprop="author">{{ quote.author|author }}</small>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{ tag }}">change</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class='{% if not quotes.has_previous %} disabled {% endif %}'
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>


                <li class="next">
                    <a class='{% if not quotes.has_next %} disable {% endif %}'
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">→</span> Next
                    </a>>
                </li>
            </ul>
        </nav>


    </div>
</div>

{% endblock %}

HW10_Django/hw_project/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% block content %}
<h1>Bye!</h1>
{% endblock %}

HW10_Django/hw_project/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block main %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

HW10_Django/hw_project/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block main %}

    <h2>Password reset complete!</h2>

{% endblock %}

HW10_Django/hw_project/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block main %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

HW10_Django/hw_project/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block main %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

HW10_Django/hw_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset Password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

HW10_Django/hw_project/users/templates/users/signin.html
{% extends 'quotes/base.html' %}

{% block content %}
<h3>Sign In</h3>

{% if form.errors %}
<span class="alert alert-danger" role="alert">
    {{ form.non_field_errors }}
</span>
{% endif %}

{% if messages %}
{% for msg in messages %}
<span class="alert {% if msg.tags %} alert-{{ msg.tags }} {% endif %}" role="alert">
    {{ msg }}
</span>
{% endfor %}
{% endif %}


<form method="post">
    {% csrf_token %}
    <div class="row mb-3">
        <label>Username</label>
        {{ form.username }}
        {% if form.errors %}
        <span class="alert alert-danger" role="alert">
            {{ form.errors.username }}
        </span>
        {% endif %}
    </div>
    <div class="row mb-3">
        <label>Password</label>
        {{ form.password }}
        <span>
            {{ form.errors.password }}
        </span>
    </div>
    <div class="small text-center">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset", class="btn btn-info">Reset</button>
</form>
{% endblock %}

HW10_Django/hw_project/users/templates/users/signup.html
{% extends 'quotes/base.html' %}

{% block content %}
<h3>Sign Up</h3>

{% if form.errors %}
<span class="alert alert-danger" role="alert">
    {{ form.non_field_errors }}
</span>
{% endif %}


<form method="post">
    {% csrf_token %}
    <div class="row mb-3">
        <label>Username</label>
        {{ form.username }}
        {% if form.errors %}
        <span class="alert alert-danger" role="alert">
            {{ form.errors.username }}
        </span>
        {% endif %}
    </div>
    <div class="row mb-3">
        <label>First name</label>
        {{ form.first_name }}
        <span>
            {{ form.errors.first_name }}
        </span>
    </div>
    <div class="row mb-3">
        <label>Last name</label>
        {{ form.last_name }}
        <span>
            {{ form.errors.last_name }}
        </span>
    </div>
    <div class="row mb-3">
        <label>Email</label>
        {{ form.email }}
        <span>
            {{ form.errors.email }}
        </span>
    </div>
    <div class="row mb-3">
        <label>Password</label>
        {{ form.password1 }}
        <span>
            {{ form.errors.password1 }}
        </span>
    </div>
        <div class="row mb-3">
        <label>Repeat password</label>
        {{ form.password2 }}
        <span>
            {{ form.errors.password2 }}
        </span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset", class="btn btn-info">Reset</button>
</form>
{% endblock %}